# Generated by Django 4.1.7 on 2023-03-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField()),
                ('quantity_in_stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
